<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>OmenCore.NvidiaPower</AssemblyName>
    <RootNamespace>NvpwrControlBlackwell</RootNamespace>
    <Version>4.4.5</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.2" />
    <InternalsVisibleTo Include="OmenCoreApp.Tests" />
    <InternalsVisibleTo Include="OmenCore" />
  </ItemGroup>
</Project>
